package com.cheatbox;

/* This class is generated by JADX */
public final class R {

    public static final class anim {
        public static final int MT_Bin = 2130771970;
    }

    public static final class animator {
        public static final int MT_Bin = 2130837504;
    }

    public static final class attr {
        public static final int MT_Bin = 2130903040;
    }

    public static final class bool {
        public static final int MT_Bin = 2130968576;
    }

    public static final class color {
        public static final int MT_Bin = 2131034112;
    }

    public static final class dimen {
        public static final int MT_Bin = 2131099648;
    }

    public static final class drawable {
        public static final int MT_Bin = 2131165184;
    }

    public static final class id {
        public static final int MT_Bin = 2131230720;
        public static final int material_clock_display = 2131230949;
        public static final int material_clock_period_toggle = 2131230956;
    }

    public static final class integer {
        public static final int MT_Bin = 2131296256;
    }

    public static final class interpolator {
        public static final int MT_Bin = 2131361792;
    }

    public static final class layout {
        public static final int MT_Bin = 2131427328;
    }

    public static final class string {
        public static final int MT_Bin = 2131689473;
    }

    public static final class style {
        public static final int MT_Bin = 2131755008;
    }

    public static final class xml {
        public static final int MT_Bin = 2131886080;
    }
}
